### ISSUE TITLE
[bug] Node can't start to syncing blocks because of can't find peers

### ISSUE THREAD

**Issue by wocorpse** [LuckyCoinProj/luckycoinV3#3]
# Bug Report

**Current behavior:**

**Expected behavior**

**Steps to reproduce:**

**Screenshots**

**Dogecoin Core version**

**Machine specs**
- OS:
- CPU:
- RAM:
- Disk size:
- Disk Type (HD/SDD):

**Extra information**

<img width="622" alt="image" src="https://github.com/user-attachments/assets/8199b298-2b65-4f50-a060-13c0a8458979">

**Comment by xsoft** [comment]
Closing is fine, but is there any peer list at all?
We too have empty peer list.

**Comment by xsoft** [comment]
It works, thanks for a peer list
```
addnode=189.1.216.178:9917
addnode=189.1.222.9:9917
```
